theme: jekyll-theme-minimal
title: Maternal Assistance Programming
description: Directly outputing assessments from CMQCC and a numerical risk prediction - see the links to the assessment forms. Additionally, python codes under the codes link can be downloaded and run. Details behind each type of assessment can be found in the methods section!


show_downloads: True
navigation:
  - title: Home
    url: /
  - title: CMQCC Assessment Form
    url: CMQCC
  - title: Antepartum Assessment Form
    url: Antepartum
  - title: Peripartum Assessment Form
    url: Peripartum  
  - title: Methods
    url: Methods
  - title: Codes
    url: Codes
  - title: Contact Information
    url: Contact
