theme: jekyll-theme-minimal
title: Maternal Assist
description: Input risk factors to output assessments from CMQCC, modified CMQCC, and numerical risk prediction.
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Assessment
    url: map
