theme: jekyll-theme-minimal
title: Maternal Assistance Programming
description: Directly outputing assessments from CMQCC and a numerical risk prediction - see the links to the assessment forms. Addditionally, can run the python codes under the codes link. Details behind each type of assessment can be found in the methods section!


show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Antepartum Assessment Form
    url: Antepartum
  - title: CMQCC Assessment Form
    url: CMQCC
  - title: Methods
    url: Methods
  - title: Codes
    url: Codes
  - title: Contact Information
    url: Contact
